### ISSUE TITLE
"State of Identity" link in Media Links section of blog is broken

### ISSUE THREAD

**Issue by Ippolito72** [build-trust/ockam-website#584]
In the Media Links article of the Blogs section of the website (under Announcements), the State of Identity link is no longer working.

https://oneworldidentity.com/podcast/ockam/

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/67592293/182895837-a4c9d215-3959-4297-bc21-2f9f3c012372.png">

**Comment by mrinalwadhwa** [comment]
@Ippolito72 thank you for reporting this.

**Comment by SaketKaswa20** [comment]
I would like to solve this, please assign me.

**Comment by SanjoDeundiak** [comment]
@SaketKaswa20 sure, but do you know what the right link is?
@mrinalwadhwa maybe you know?

**Comment by SaketKaswa20** [comment]
I didn't get the link, I searched on the web.

**Comment by nazmulidris** [comment]
@mrinalwadhwa is this the correct link for the podcast? https://www.listennotes.com/podcasts/state-of-identity/ockam-architecture-for-trust-XiSK7MqfVmP/

**Comment by nazmulidris** [comment]
@SaketKaswa20 here are the changes that need to be made to `/ockam-website/src/content/blog/media_links.mdx` if you would like to make them.

1. In the `## Podcasts` section, here's the new link `[State of Identity](https://open.spotify.com/episode/2Mhx0QHPedkvXpz4YPc4Hm)`

2. In the `## Blog Posts and Articles` section, the line `
[State of Identity](https://oneworldidentity.com/podcast/ockam/)` needs to be removed.

Thanks 👍🏽

**Comment by nazmulidris** [comment]
@SaketKaswa20 - We have decided to remove old links from the website. I am going to close this issue as there's a PR on the way to remove these old links.

Thank you for spending time on this. In order to make contributions to Ockam (now or in the
future), please add yourself to the Contributor License Agreement.

- Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

- The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified. The video below shows this in action.

https://github.com/build-trust/ockam-website/assets/2966499/363b5416-3b08-40fc-94b7-ce5ed3fb5af3

cc: @mrinalwadhwa

**Comment by SaketKaswa20** [comment]
Sure, I'll do it. Thank you :)

**Comment by SaketKaswa20** [comment]
Made the pull request.

**Comment by nazmulidris** [comment]
> Made the pull request.

Excellent! Thanks for adding yourself to the CONTRIBUTORS.csv file 👏🏽 . Someone from our team will approve your PR soon 👍🏽 .

https://github.com/build-trust/ockam-contributors/pull/257
